### ISSUE TITLE
Deserialization of ContentProtection?

### ISSUE THREAD

**Issue by steamyalt** [emarsden/dash-mpd-rs#1]
Even though a `ContentProtection` struct exists, it is not deserialized as part of the `AdaptationSet` struct.
Is there any reason for this?

Furthermore, I'd be interested in deserializing `ContentProtection` with the following structure, which currently isn't possible:
```xml
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>Base64Data==</cenc:pssh>
      </ContentProtection>
```
Adding both the `schemeIdUri` and `cenc:pssh` fields to `ContentProtection` would be appreciated.

**Comment by emarsden** [comment]
Thanks for your suggestion. I've now made sure `ContentProtection` is deserialized, and added the `cenc_pssh` field which should be deserialized to a String (no attempt to decode base64). Support for cenc:pssh is not very robust because there is no XML namespace support in the serde crate that we are using for deserialization, but I think it will work in practice for most MPD manifests in the wild.
