### ISSUE TITLE
Allow async HTTP

### ISSUE THREAD

**Issue by holly-hacker** [emarsden/dash-mpd-rs#5]
dash_mpd currently uses blocking HTTP when downloading a stream which can cause problems in async applications. Is there an intent to support async HTTP?

**Comment by holly-hacker** [comment]
To be more specific, I get the following panic when creating an instance of the blocking reqwest client in an async function:
```
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
```

**Comment by emarsden** [comment]
Thanks for your patch. I do intend to allow async use, and indeed probably use async internally to allow parallel downloading of media segments. This will unfortunately be a breaking API change so I want to think carefully about the future API (possibly allowing pluggable HTTP support, for example).

**Comment by ArjixWasTaken** [comment]
> This will unfortunately be a breaking API change so I want to think carefully about the future API (possibly allowing pluggable HTTP support, for example).

That is not a concern, since users can just keep using an older version.

**Comment by holly-hacker** [comment]
> > This will unfortunately be a breaking API change so I want to think carefully about the future API (possibly allowing pluggable HTTP support, for example).
> 
> That is not a concern, since users can just keep using an older version.

While you can obviously make breaking API changes with a major version bump, you should do so cautiously because it comes with manual changes from the side of users that wish to upgrade (and older versions typically don't get bugfixes). Also, maintaining open source software usually isn't a paid job so you'll need to have some patience :)

**Comment by ArjixWasTaken** [comment]
Please don't think that I am asking you to do it on your own, in the first place I forked the fork that has the patches so I can work on it on my own to make it a non-breaking change (if it is easy enough).

The only reason I sent a message here was to make you reconsider so that in the future you will merge my PR.
And yes I know that it isn't a paid job for you, I don't need you to tell me, I wasn't even being rude to you.

**Comment by ArjixWasTaken** [comment]
my fork might not have any commits yet, because I haven't pushed yet

**Comment by ArjixWasTaken** [comment]
(just noticed that you are not the author, and I was replying to the author, oof)

**Comment by emarsden** [comment]
Concerning the API change, I'm looking at using the [tower_http](https://crates.io/crates/tower-http) middleware stack together with hyper, or perhaps instead the [reqwest-middleware](https://crates.io/crates/reqwest-middleware) crate. The former is a bigger change, but seems to have more momentum behind it. 

If you need async support immediately (sorry to be slow working on this, I've mostly been looking at subtitle support), it should be very easy to port forward @holly-hacker's fork, very few changes are required to the current code.

**Comment by emarsden** [comment]
I have now implemented async support using the async (standard) Client in the reqwest crate, pretty much exactly like @holly-hacker's patch (thanks!). This will soon be v0.7.0 (API change). 

I finally decided not to use hyper with tower_http, because the upcoming hyper version will remove the high-level API and the low-level API is not well suited.
