### ISSUE TITLE
Default microsoft playready namespace causing issues with our MPDs

### ISSUE THREAD

**Issue by sbuzzard** [emarsden/dash-mpd-rs#86]
In the latest release 0.17.4, a namespace is added to all MPDs on serialization, even if it is not set ([from this PR](https://github.com/emarsden/dash-mpd-rs/commit/56c6a2058be0e150fd055f5700fb2550bdbc6a83).  I'm wondering if there is an alternative since it's causing a bit of havoc with some of our systems.  If it could be put into a feature perhaps.  I have no urgent need to upgrade to 0.17.4 but would like to at some point, lol.   I know dash-mpd-rs does this for standards like w3 and mpeg changes.  If we want to keep it, that's fine and we can override in our serialization function to the empty string.   Not sure there's a way currently to force it to None currently right?

**Comment by emarsden** [comment]
Yes, the mspr: namespace is now defined, in the same way as for xlink: and cenc: namespaces. Ideally these would only be added when they are used in the manifest, but the quick-xml serialization machinery doesn't seem to allow us to do that.

I'd be hesitant to add special workarounds/extra features for this, because I think the resulting manifests are not invalid in this respect. 

BTW, I'm also working on improving XSD conformance by correcting element ordering, and fixing the type of some struct elements (Option to Vec in a few cases). This will be in a 0.18 release.

**Comment by sbuzzard** [comment]
okay, closing ...
